version: '2'
services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8081:8081
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:latest
        restart: always
 
    node:
        depends_on:
            - reverseproxy
        image: nrs-tutorijal6:latest
        ports:
            - 3000:3000
        restart: always
    
    bulletin:
        depends_on:
            - reverseproxy
        image: bulletin-board-app:latest